server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8190/
          predicates:
            - Path=/coreMS/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-core-service
#            - JwtAuthFilter
        - id: images-service
          uri: http://localhost:8166/
          predicates:
            - Path=/imagesMS/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-images-service
#            - JwtAuthFilter
#        - id: auth-service
#          uri: http://localhost:8188/
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/web-new-booking-auth
#            - JwtAuthFilter

#jwt:
#  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
