server:
  port: 8166
  servlet:
    context-path: /web-images-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kv_startUp_images
    username: kv_admin
    password: kv_admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: info
    ru.get: debug
    org.springframework.web: info
    org.hibernate: error
  file:
    name: ./Logs/core.log
  charset:
    console: UTF-8
    file: UTF-8